import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";



const montserrat = Montserrat({
  variable:'--font-montserrat',
  subsets : ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Sidebar>
          {children}
        </Sidebar>
        <div>
          <h1>This is where player container at</h1>
        </div>
      </body>
    </html>
  );
}
